### ISSUE TITLE
list_ticker_news misuses published_utc.* values

### ISSUE THREAD

**Issue by knubbe** [massive-com/client-python#391]
**Describe the bug**

Controlling the `published_utc` parameter requires passing le/ge filters as e.g. `published_utc.gt`. However, the python library passes them incorrectly as `published.utc_gt`. This makes the backend HTTP API to ignore the parameter as whole, as it does not recognize it.

**To Reproduce**
Simply use any of the documented `published_utc_gt` type of input parameters through the RESTClient::list_ticker_news().

**Comment by justinpolygon** [comment]
Hey @knubbe, I suspect we just fixed this via https://github.com/polygon-io/client-python/pull/389. Do you mind checking out the latest v1.7.2 release and see if that fixes the issue. There is also a workaround listed in https://github.com/polygon-io/client-python/issues/382 that you can probably use without updating too (since I know that can be a pain sometimes).
